import 'package:flutter/material.dart';
import '../models/domain_models.dart';
import '../repositories/street_repository.dart';

class MessagesScreen extends StatelessWidget { const MessagesScreen({super.key});
  @override Widget build(BuildContext context) => SafeArea(child: FutureBuilder<List<Conversation>>(future: MockStreetRepository().getConversations(), builder: (_, snapshot) { if (!snapshot.hasData) return const Center(child: CircularProgressIndicator()); return ListView(padding: const EdgeInsets.all(22), children: [const SizedBox(height: 10), const Text('Mensagens', style: TextStyle(fontSize: 32, fontWeight: FontWeight.w800)), const SizedBox(height: 8), const Text('Interface demonstrativa, preparada para integração futura.', style: TextStyle(color: Colors.white60)), const SizedBox(height: 25), ...snapshot.data!.map((chat) => Card(child: ListTile(contentPadding: const EdgeInsets.all(15), leading: CircleAvatar(child: Text(chat.name[0])), title: Text(chat.name, style: const TextStyle(fontWeight: FontWeight.w700)), subtitle: Text(chat.lastMessage, maxLines: 1, overflow: TextOverflow.ellipsis), trailing: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Text(chat.time, style: const TextStyle(fontSize: 10)), if (chat.unread > 0) Badge(label: Text('${chat.unread}'))]), onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => ChatScreen(conversation: chat)))))]); }));
}
class ChatScreen extends StatefulWidget { const ChatScreen({super.key, required this.conversation}); final Conversation conversation; @override State<ChatScreen> createState() => _ChatScreenState(); }
class _ChatScreenState extends State<ChatScreen> { final message = TextEditingController(); @override void dispose() { message.dispose(); super.dispose(); } @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text(widget.conversation.name)), body: SafeArea(child: Column(children: [Expanded(child: ListView(padding: const EdgeInsets.all(18), children: const [Align(alignment: Alignment.centerLeft, child: Chip(label: Text('Olá! Gostaria de falar sobre o evento.'))), Align(alignment: Alignment.centerRight, child: Chip(label: Text('Claro, vamos conversar.')))])), Padding(padding: const EdgeInsets.all(12), child: Row(children: [Expanded(child: TextField(controller: message, maxLength: 500, decoration: const InputDecoration(hintText: 'Escreva uma mensagem...', counterText: ''))), IconButton.filled(onPressed: () { message.clear(); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Envio pendente de integração com o back-end.'))); }, icon: const Icon(Icons.send))]))]))); }
